# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.synced_folder 'puppet', '/puppet'
    config.vm.synced_folder '.', '/vagrant', disabled: true
    sharePath = '/mnt/vshare'
    config.vm.synced_folder 'share', sharePath, create: true

    config.vm.box = 'puppetlabs/centos-7.0-64-puppet-enterprise'

    # Ambari master node provisioning.
    config.vm.define 'puppet.dev', primary: true do |puppetdev|
      puppetdev.vm.hostname = 'puppet.dev'
      puppetdev.vm.network :public_network

      puppetdev.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
      end

#      ambariserver.vm.provision :puppet do |puppet|
#        puppet.manifests_path   = 'puppet/manifests'
#        puppet.module_path      = 'puppet/modules'
#        puppet.manifest_file    = 'ambariserver.pp'
#        puppet.options          = '--verbose'
#        puppet.facter           = {
#            'master_hostname'     => master_hostname,
#            'node_base_name'      => node_base_name,
#            'domain_subfix'       => domain_subfix,
#            'base_ip'             => base_ip,
#            'cluster_size'        => cluster_size,
#            'share_path'          => sharePath,
#        }
#      end
    end

end
